const CURRICULUM_AREAS={
'I° Medio':['Biología','Física','Química'],
'II° Medio':['Biología','Física','Química'],
'III° Medio':['Bienestar y Salud','Seguridad, Prevención y Autocuidado','Ambiente y Sostenibilidad','Tecnología y Sociedad','Habilidades científicas transversales']
};
const CURRICULUM_KEY='cd_curriculum_v02';
const TRACK_KEY='cd_curriculum_tracking_v02';
const readJSON=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
let records=readJSON(CURRICULUM_KEY,[]);
let tracking=readJSON(TRACK_KEY,{});
const saveCurriculum=()=>localStorage.setItem(CURRICULUM_KEY,JSON.stringify(records));
const saveTracking=()=>localStorage.setItem(TRACK_KEY,JSON.stringify(tracking));
const courseSelect=document.getElementById('curso');
const areaSelect=document.getElementById('area');
const list=document.getElementById('oa-list');
const query=document.getElementById('oa-search');
const statusFilter=document.getElementById('oa-status');
const summary=document.getElementById('oa-summary');
const alertBox=document.getElementById('oa-message');
function message(text){alertBox.textContent=text;}
async function loadBundledCurriculum(){try{const res=await fetch('curriculum_oficial.json',{cache:'no-cache'});if(!res.ok)throw Error('HTTP '+res.status);const official=(await res.json()).map(validateRecord);const custom=readJSON(CURRICULUM_KEY,[]);const combined=new Map(official.map(r=>[r.id,r]));for(const r of custom)if(!combined.has(r.id))combined.set(r.id,r);records=[...combined.values()];message(`Repertorio cargado: ${official.length} OA. En III° Medio los indicadores específicos deben verificarse por actividad o evaluación.`);renderRecords();window.dispatchEvent(new Event('cd-data-updated'))}catch(e){message('No se pudo cargar el repertorio: '+e.message)}}
function renderAreas(){areaSelect.innerHTML=CURRICULUM_AREAS[courseSelect.value].map(area=>`<option value="${escapeHTML(area)}">${escapeHTML(area)}</option>`).join('');renderRecords();}
function renderRecords(){
 const term=query.value.trim().toLocaleLowerCase('es');
 const filtered=records.filter(r=>r.curso===courseSelect.value&&r.area===areaSelect.value&&[r.codigo,r.descripcion,...r.indicadores].join(' ').toLocaleLowerCase('es').includes(term)&&(statusFilter.value==='Todos'||(tracking[r.id]?.estado||'Pendiente')===statusFilter.value));
 summary.textContent=`${filtered.length} OA encontrados · ${records.length} OA importados en total`;
 list.innerHTML=filtered.length?filtered.map(r=>{
 const t=tracking[r.id]||{};
 return `<article class="card oa-card"><div class="oa-head"><span class="oa-code">${escapeHTML(r.codigo)}</span><span class="oa-source">${escapeHTML(r.fuenteTipo)}</span></div><p>${escapeHTML(r.descripcion)}</p><details><summary>Indicadores de evaluación (${r.indicadores.length})</summary>${r.indicadores.length?`<ul>${r.indicadores.map(i=>`<li>${escapeHTML(i)}</li>`).join('')}</ul>`:'<p>El programa no presenta aquí una lista de indicadores individualizada para este OA. Consultar orientaciones y evaluaciones del módulo.</p>'}</details><p class="source"><a href="${escapeHTML(r.fuenteUrl)}" target="_blank" rel="noopener noreferrer">Consultar fuente ↗</a></p><label for="state-${escapeHTML(r.id)}">Seguimiento</label><select data-track="${escapeHTML(r.id)}" id="state-${escapeHTML(r.id)}"><option ${(!t.estado||t.estado==='Pendiente')?'selected':''}>Pendiente</option><option ${t.estado==='En desarrollo'?'selected':''}>En desarrollo</option><option ${t.estado==='Trabajado'?'selected':''}>Trabajado</option></select><label>Notas docentes</label><textarea data-note="${escapeHTML(r.id)}" rows="2" placeholder="Actividades, evaluaciones, observaciones...">${escapeHTML(t.nota||'')}</textarea><button data-use="${escapeHTML(r.id)}" class="primary">Usar en asistente</button></article>`}).join(''):'<div class="card"><b>No hay OA cargados para este filtro.</b><p>Importa registros verificados del MINEDUC mediante un archivo JSON. No se incluyen OA de demostración como si fueran oficiales.</p></div>';
}
function validURL(u){try{const x=new URL(u);return ['https:','http:'].includes(x.protocol)}catch{return false}}
function validateRecord(r){if(!r||typeof r!=='object')throw Error('Registro no válido');const required=['id','curso','area','codigo','descripcion','indicadores','fuenteUrl','fuenteTipo'];for(const k of required){if(!(k in r))throw Error(`Falta el campo ${k}`)}if(!CURRICULUM_AREAS[r.curso]?.includes(r.area))throw Error('Curso o área no reconocida');if(!Array.isArray(r.indicadores)||!r.indicadores.every(i=>typeof i==='string'&&i.trim()))throw Error('Indicadores inválidos');if(!validURL(r.fuenteUrl))throw Error('URL de fuente inválida');for(const k of ['id','codigo','descripcion','fuenteTipo'])if(typeof r[k]!=='string'||!r[k].trim())throw Error(`Campo inválido: ${k}`);return {id:r.id.trim(),curso:r.curso,area:r.area,codigo:r.codigo.trim(),descripcion:r.descripcion.trim(),indicadores:r.indicadores.map(x=>x.trim()),fuenteUrl:r.fuenteUrl,fuenteTipo:r.fuenteTipo};}
document.getElementById('oa-import').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2000000)throw Error('Archivo demasiado grande (máximo 2 MB)');const parsed=JSON.parse(await file.text());if(!Array.isArray(parsed))throw Error('El JSON debe contener una lista de OA');const validated=parsed.map(validateRecord);if(new Set(validated.map(r=>r.id)).size!==validated.length)throw Error('Hay identificadores repetidos');const merged=new Map(records.map(r=>[r.id,r]));validated.forEach(r=>merged.set(r.id,r));records=[...merged.values()];saveCurriculum();window.dispatchEvent(new Event('cd-data-updated'));message(`Se importaron ${validated.length} registros. Revisa que su contenido corresponda a la fuente oficial.`);renderRecords()}catch(err){message(`No se pudo importar: ${err.message}`)}finally{e.target.value=''}});
document.getElementById('oa-export').onclick=()=>{const blob=new Blob([JSON.stringify(records,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cienciadesk-curriculum.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
document.getElementById('oa-example').onclick=()=>{const blob=new Blob([JSON.stringify([{id:'CN1M-OA-XX',curso:'I° Medio',area:'Biología',codigo:'CN1M OA XX',descripcion:'REEMPLAZAR POR EL TEXTO OFICIAL DEL OA',indicadores:['REEMPLAZAR POR EL INDICADOR OFICIAL'],fuenteUrl:'https://www.curriculumnacional.cl/',fuenteTipo:'Plantilla sin validar'}],null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='plantilla-curricular.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
list.addEventListener('change',e=>{const id=e.target.dataset.track;if(id){tracking[id]={...(tracking[id]||{}),estado:e.target.value};saveTracking();renderRecords();window.dispatchEvent(new Event('cd-data-updated'))}});
list.addEventListener('input',e=>{const id=e.target.dataset.note;if(id){tracking[id]={...(tracking[id]||{}),nota:e.target.value};saveTracking();renderRecords();window.dispatchEvent(new Event('cd-data-updated'))}});
list.addEventListener('click',e=>{const id=e.target.dataset.use;if(!id)return;const r=records.find(x=>x.id===id);if(!r)return;document.getElementById('oa').value=`${r.codigo}: ${r.descripcion}`;document.getElementById('indicador').value=r.indicadores.join('\n');document.querySelector('[data-tab="asistente"]').click();});
courseSelect.addEventListener('change',renderAreas);areaSelect.addEventListener('change',renderRecords);query.addEventListener('input',renderRecords);statusFilter.addEventListener('change',renderRecords);window.addEventListener('cd-restored',()=>{records=readJSON(CURRICULUM_KEY,[]);tracking=readJSON(TRACK_KEY,{});renderRecords()});renderAreas();loadBundledCurriculum();
