const CURRICULUM_AREAS={'I° Medio':['Biología','Física','Química'],'II° Medio':['Biología','Física','Química'],'III° Medio':['Bienestar y Salud','Seguridad, Prevención y Autocuidado','Ambiente y Sostenibilidad','Tecnología y Sociedad','Habilidades científicas transversales']};
const CURRICULUM_KEY='cd_curriculum_v02',TRACK_KEY='cd_curriculum_tracking_v02';
const readJSON=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let records=readJSON(CURRICULUM_KEY,[]),tracking=readJSON(TRACK_KEY,{}),selectedId=null;
const saveTracking=()=>localStorage.setItem(TRACK_KEY,JSON.stringify(tracking));
const courseSelect=document.getElementById('curso'),areaSelect=document.getElementById('area'),list=document.getElementById('oa-list'),detail=document.getElementById('oa-detail'),query=document.getElementById('oa-search'),statusFilter=document.getElementById('oa-status'),summary=document.getElementById('oa-summary'),alertBox=document.getElementById('oa-message');
function message(s){alertBox.textContent=s}
function validURL(u){try{return ['http:','https:'].includes(new URL(u).protocol)}catch{return false}}
function validateRecord(r){if(!r||typeof r!=='object')throw Error('Registro inválido');for(const k of ['id','curso','area','codigo','descripcion','indicadores','fuenteUrl','fuenteTipo'])if(!(k in r))throw Error('Falta '+k);if(!CURRICULUM_AREAS[r.curso]?.includes(r.area)||!Array.isArray(r.indicadores)||!r.indicadores.every(x=>typeof x==='string')||!validURL(r.fuenteUrl))throw Error('Datos curriculares inválidos');return r}
async function loadBundledCurriculum(){try{const res=await fetch('curriculum_oficial.json',{cache:'no-cache'});if(!res.ok)throw Error('HTTP '+res.status);const official=(await res.json()).map(validateRecord);const custom=readJSON(CURRICULUM_KEY,[]);const map=new Map(official.map(r=>[r.id,r]));for(const r of custom)if(!map.has(r.id))map.set(r.id,r);records=[...map.values()];message(`${official.length} OA cargados`);renderRecords();window.dispatchEvent(new Event('cd-data-updated'))}catch(e){message('No se pudo cargar: '+e.message);renderRecords()}}
function renderAreas(){areaSelect.innerHTML=CURRICULUM_AREAS[courseSelect.value].map(x=>`<option>${escapeHTML(x)}</option>`).join('');selectedId=null;renderRecords()}
function filteredRecords(){const q=query.value.trim().toLocaleLowerCase('es');return records.filter(r=>r.curso===courseSelect.value&&r.area===areaSelect.value&&[r.codigo,r.descripcion,...r.indicadores].join(' ').toLocaleLowerCase('es').includes(q)&&(statusFilter.value==='Todos'||(tracking[r.id]?.estado||'Pendiente')===statusFilter.value))}
function renderRecords(){const a=filteredRecords();summary.textContent=`${a.length} resultados`;list.innerHTML=a.length?a.map(r=>`<button class="oa-row ${r.id===selectedId?'selected':''}" data-select="${escapeHTML(r.id)}" aria-pressed="${r.id===selectedId}"><span class="code">${escapeHTML(r.codigo.replace(/^.*?(OA\s*\d+).*$/i,'$1'))}</span><span><span class="excerpt">${escapeHTML(r.descripcion)}</span><span class="row-meta">${r.indicadores.length} indicadores · ${escapeHTML(tracking[r.id]?.estado||'Pendiente')}</span></span></button>`).join(''):'<div class="panel panel-body">No hay objetivos con estos filtros.</div>';if(selectedId&&!a.some(r=>r.id===selectedId))selectedId=null;renderDetail()}
function renderDetail(){const r=records.find(x=>x.id===selectedId);if(!r){detail.innerHTML='<div class="empty-detail"><span>▤</span><h2>Selecciona un objetivo</h2><p>Aquí aparecerán su descripción, indicadores y seguimiento.</p></div>';return}const t=tracking[r.id]||{},checked=t.indicadores||[];detail.innerHTML=`<div class="detail-top"><span class="pill">${escapeHTML(r.codigo)}</span><a class="source-link" href="${escapeHTML(r.fuenteUrl)}" target="_blank" rel="noopener noreferrer">Fuente ↗</a></div><h2>Objetivo de aprendizaje</h2><p class="oa-description">${escapeHTML(r.descripcion)}</p><h3>Indicadores de evaluación <span class="muted">(${r.indicadores.length})</span></h3>${r.indicadores.length?`<ul class="ind-list">${r.indicadores.map((v,i)=>`<li class="${checked.includes(i)?'checked':''}"><input type="checkbox" data-ind="${i}" aria-label="Marcar indicador ${i+1}" ${checked.includes(i)?'checked':''}><span>${escapeHTML(v)}</span></li>`).join('')}</ul>`:'<p class="muted">No hay indicadores individualizados asociados a este OA en el repertorio actual. Consulta las actividades del programa.</p>'}<h3>Seguimiento docente</h3><label for="detail-state">Estado del OA</label><select id="detail-state">${['Pendiente','En desarrollo','Trabajado'].map(x=>`<option ${x===(t.estado||'Pendiente')?'selected':''}>${x}</option>`).join('')}</select><label for="detail-note">Notas y planificación</label><textarea id="detail-note" rows="3" placeholder="Observaciones, actividades, evaluaciones...">${escapeHTML(t.nota||'')}</textarea><div class="detail-actions"><button class="primary" id="detail-use">Usar en asistente ↗</button></div>`}
list.addEventListener('click',e=>{const btn=e.target.closest('[data-select]');if(!btn)return;selectedId=btn.dataset.select;renderRecords();if(innerWidth<951)document.querySelector('.detail-column').scrollIntoView({behavior:'smooth',block:'start'})});
detail.addEventListener('change',e=>{if(!selectedId)return;const t=tracking[selectedId]||{};if(e.target.id==='detail-state')t.estado=e.target.value;if(e.target.dataset.ind!==undefined){const idx=Number(e.target.dataset.ind);const a=new Set(t.indicadores||[]);e.target.checked?a.add(idx):a.delete(idx);t.indicadores=[...a]}tracking[selectedId]=t;saveTracking();renderRecords();window.dispatchEvent(new Event('cd-data-updated'))});
detail.addEventListener('input',e=>{if(e.target.id!=='detail-note'||!selectedId)return;tracking[selectedId]={...(tracking[selectedId]||{}),nota:e.target.value};saveTracking()});
detail.addEventListener('click',e=>{if(e.target.id!=='detail-use')return;const r=records.find(x=>x.id===selectedId);if(!r)return;document.getElementById('oa').value=`${r.codigo}: ${r.descripcion}`;const checked=tracking[r.id]?.indicadores||[];document.getElementById('indicador').value=(checked.length?checked.map(i=>r.indicadores[i]):r.indicadores).filter(Boolean).join('\n');document.querySelector('[data-tab="asistente"]').click()});
courseSelect.addEventListener('change',renderAreas);areaSelect.addEventListener('change',()=>{selectedId=null;renderRecords()});query.addEventListener('input',renderRecords);statusFilter.addEventListener('change',renderRecords);
function downloadJSON(name,data){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)}
document.getElementById('oa-export').onclick=()=>downloadJSON('cienciadesk-curriculum.json',records);
document.getElementById('oa-example').onclick=()=>downloadJSON('plantilla-curricular.json',[{id:'CN1M-OA-XX',curso:'I° Medio',area:'Biología',codigo:'CN1M OA XX',descripcion:'REEMPLAZAR CON TEXTO OFICIAL',indicadores:['REEMPLAZAR CON INDICADOR'],fuenteUrl:'https://www.curriculumnacional.cl/',fuenteTipo:'Plantilla sin validar'}]);
document.getElementById('oa-import').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>2000000)throw Error('Máximo 2 MB');const a=JSON.parse(await f.text());if(!Array.isArray(a))throw Error('Debe ser una lista');a.forEach(validateRecord);if(new Set(a.map(r=>r.id)).size!==a.length)throw Error('Identificadores duplicados');const merged=new Map(records.map(r=>[r.id,r]));a.forEach(r=>merged.set(r.id,r));records=[...merged.values()];localStorage.setItem(CURRICULUM_KEY,JSON.stringify(records));renderRecords();message(`${a.length} registros importados`);window.dispatchEvent(new Event('cd-data-updated'))}catch(err){message('Error: '+err.message)}finally{e.target.value=''}});
window.addEventListener('cd-restored',()=>{records=readJSON(CURRICULUM_KEY,[]);tracking=readJSON(TRACK_KEY,{});renderRecords();loadBundledCurriculum()});renderAreas();loadBundledCurriculum();